# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Searchub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Searchub
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'SDWebImage'
  pod 'CCBottomRefreshControl'

end
